from pathlib import Path

from mixer_tts_onnx import MixerTTS


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    model_path = repo_root / "checkpoints" / "onnx" / "mixer_lj_80_vocos.onnx"
    tts = MixerTTS(model_path)
    out = Path(__file__).resolve().parent / "hello_world.wav"
    tts.create(
        "Hello world. This audio was generated by the Mixer TTS ONNX wrapper.",
        output_path=out,
        speed=1.0,
    )
    print(out)


if __name__ == "__main__":
    main()
